import { Josefin_Slab } from 'next/font/google';

import type { Metadata } from 'next';

import 'the-new-css-reset/css/reset.css';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  display: 'swap',
});

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props): JSX.Element => {
  return (
    <html lang="en" className={josefinSlab.className}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
